################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
- sections:
    - title: Getting Started
      link: docs/getting-started.md
      open: true
    - title: Release-Notes
      link: docs/release-notes/release-notes.md
      open: true
- sections:
    - title: API Reference
      link: null
      open: true
      sections:
        - title: Account Management
          sections:
            - title: Add Memo Line
              link: docs/APIs/Account-Management/Add-Memo-Line.md
            - title: Block Unblock Account
              link: docs/APIs/Account-Management/Block-Unblock-Account.md
            - title: Board Account
              link: docs/APIs/Account-Management/Board-Account.md
            - title: Inquire Account
              link: docs/APIs/Account-Management/Inquire-Account.md
            - title: Inquire Account Plan
              link: docs/APIs/Account-Management/Inquire-Account-Plan.md
            - title: Inquire Behavioural History
              link: docs/APIs/Account-Management/Inquire-Behavioural-History.md
            - title: Inquire Delinquency
              link: docs/APIs/Account-Management/Inquire-Delinquency.md
            - title: Inquire Direct Debit Controls
              link: docs/APIs/Account-Management/Inquire-Direct-Debit-Controls.md
            - title: Inquire Payment History
              link: docs/APIs/Account-Management/Inquire-Payment-History.md
            - title: Inquire Statement Plan Details
              link: docs/APIs/Account-Management/Inquire-Statement-Plans.md
            - title: Inquire Statement Transaction Details
              link: docs/APIs/Account-Management/Inquire-Statement-Transactions.md
            - title: List Billed Transactions
              link: docs/APIs/Account-Management/List-billed-Transactions.md
            - title: List Cards By Account
              link: docs/APIs/Account-Management/List-Cards-by-Account.md
            - title: List Memos
              link: docs/APIs/Account-Management/List-Memo.md
            - title: List Outstanding Authorizations
              link: docs/APIs/Account-Management/List-Outstanding-Authorizations.md
            - title: List Plans
              link: docs/APIs/Account-Management/List-Plans.md
            - title: List Unbilled Transactions
              link: docs/APIs/Account-Management/List-unbilled-Transactions.md
            - title: Monetary-Action
              link: docs/APIs/Account-Management/Monetary-Action.md
            - title: Post Payments
              link: docs/APIs/Account-Management/Post-Payments.md
            - title: Product Transfer
              link: docs/APIs/Account-Management/Product-Transfer.md
            - title: Transfer Plan Balance
              link: docs/APIs/Account-Management/Transfer-Plan-Balance.md
            - title: Update Account Charge-Off
              link: docs/APIs/Account-Management/Update-Account-Charge-Off.md
            - title: Update Billing Cycle
              link: docs/APIs/Account-Management/Update-Billing-Cycle.md
            - title: Update Credit Limit
              link: docs/APIs/Account-Management/Update-Credit-Limit.md
            - title: Update Customers' Profile
              link: docs/APIs/Account-Management/Update-Customers-Profile.md
            - title: Update Direct Debit Controls
              link: docs/APIs/Account-Management/Update-Direct-Debit-Controls.md
            - title: Update Pricing Control
              link: docs/APIs/Account-Management/Update-Pricing-Control.md
            - title: Update Statement Preference
              link: docs/APIs/Account-Management/Update-Statement-Preference.md
            - title: Update Temporary Credit Limit
              link: docs/APIs/Account-Management/Update-Temporary-Credit-Limit.md
            - title: Update Token Suppression Indicator
              link: docs/APIs/Account-Management/Update-Token-Suppress-Indicator.md
            - title: Update Waive Fee
              link: docs/APIs/Account-Management/Update-Waive-Fee.md
            - title: Inquire Account Preference
              link: docs/APIs/Account-Management/Inquire-Account-Preference.md
            - title: Update Account Preference
              link: docs/APIs/Account-Management/Update-Account-Preference.md
            - title: List Transactions by Date Range
              link: docs/APIs/Account-Management/List-Transactions-by-Date-Range.md
        - title: Authorization
          sections:
            - title: Request Authorization
              link: docs/APIs/Authorization/Request-Auth.md
            - title: Inquire Authorization Details
              link: docs/APIs/Authorization/Inquire-Authorization-Details.md              
        - title: Card Management
          sections:
            - title: Activate Card
              link: docs/APIs/Card-Management/Activate-Card.md
            - title: Block Unblock Card
              link: docs/APIs/Card-Management/Block-Card.md
            - title: Board Card
              link: docs/APIs/Card-Management/Board-Card.md
            - title: Change PIN
              link: docs/APIs/Card-Management/PIN-Block-Change.md
            - title: Fetch Clear PAN from Token PAN
              link: docs/APIs/Card-Management/Fetch-Clear-PAN-From-Token-PAN.md
            - title: Fetch Token PAN from Clear PAN
              link: docs/APIs/Card-Management/Fetch-Token-PAN-from-Clear-PAN.md
            - title: Inquire Card
              link: docs/APIs/Card-Management/Inquire-Card.md
            - title: Inquire Card Controls
              link: docs/APIs/Card-Management/Inquire-Card-Controls.md
            - title: Inquire Spend Limits
              link: docs/APIs/Card-Management/Inquire-Spend-Limits.md
            - title: Inquire Card Spend Statistics
              link: docs/APIs/Card-Management/Inquire-card-spend-statistics.md
            - title: List Visa Tokens
              link: docs/APIs/Card-Management/List-Visa-Token.md
            - title: Transfer Lost Stolen Card
              link: docs/APIs/Card-Management/Lost-Stolen-Card-Transfer.md
            - title: Update Card Action
              link: docs/APIs/Card-Management/Update-Card-Action.md
            - title: Update Card Controls
              link: docs/APIs/Card-Management/Update-Card-Controls.md
            - title: Update Card Type
              link: docs/APIs/Card-Management/CardType-Update.md
            - title: Update Issue Reissue Delivery Option
              link: >-
                docs/APIs/Card-Management/Update-Issue-Reissue-Delivery-Option.md
            - title: Update Spend Limits
              link: docs/APIs/Card-Management/Update-Spend-Limits.md
            - title: Validate CVV2
              link: docs/APIs/Card-Management/CVV2-Validation.md
            - title: Generate Dynamic CVV2
              link: docs/APIs/Card-Management/Generate-Dynamic-CVV2.md
            - title: Inquire Card Preference
              link: docs/APIs/Card-Management/Inquire-Card-Preference.md
            - title: Inquire Dynamic CVV2
              link: docs/APIs/Card-Management/Inquire-Dynamic-CVV2.md
            - title: Push Provisioning
              link: docs/APIs/Card-Management/Push-Provisioning.md
            - title: Update Card Preference
              link: docs/APIs/Card-Management/Update-Card-Preference.md
            - title: Update Visa Token Status
              link: docs/APIs/Card-Management/Update-Visa-Token-Status.md             
        - title: Customer Management
          sections:
            - title: Board Customer
              link: docs/APIs/Customer-Management/Board-Customer.md
            - title: Inquire Customer
              link: docs/APIs/Customer-Management/Customer-Demographic-Inquiry.md
            - title: List Customers' Accounts
              link: docs/APIs/Customer-Management/List-Customers-Accounts.md
            - title: List Customers' Cards
              link: docs/APIs/Customer-Management/List-Customers-Cards.md
            - title: List Customers' Cards and Accounts
              link: >-
                docs/APIs/Customer-Management/List-Customer-Cards-And-Accounts.md
            - title: Fetch Customer ID from Clear PAN
              link: docs/APIs/Customer-Management/Fetch-CustomerId-From-Clear-PAN.md
            - title: List External Customers' Cards And Accounts
              link: docs/APIs/Customer-Management/List-External-Customer-Cards-And-Accounts.md    
            - title: Search Customer
              link: docs/APIs/Customer-Management/Search-Customer.md
            - title: Update Customer
              link: docs/APIs/Customer-Management/Customer-Demographic-Update.md
        - title: Miscellaneous
          sections:
            - title: Board Entities
              link: docs/APIs/Miscellaneous/Board-Entities.md
            - title: Check Health
              link: docs/APIs/Miscellaneous/Check-Health.md
            - title: Inquire Billing Cycle Assignment
              link: docs/APIs/Miscellaneous/Inquire-Billing-Cycle-Assignment.md
            - title: Inquire Business Unit
              link: docs/APIs/Miscellaneous/Inquire-Business-Unit.md
        - title: Product Management
          sections:
            - title: Inquire Interest Table
              link: docs/APIs/Product-Management/Inquire-Interest-Table.md
            - title: Inquire Plan Master
              link: docs/APIs/Product-Management/Inquire-Plan-Master.md
            - title: Inquire Product
              link: docs/APIs/Product-Management/Inquire-Product.md
            - title: Update Product Card Controls
              link: docs/APIs/Product-Management/Update-Logo-Card-Controls.md
            - title: Inquire Service Charge Table
              link: docs/APIs/Product-Management/Inquire-Service-Charge-Table.md
        - title: Security
          sections:
            - title: Get Access Token
              link: docs/APIs/Security/get-access-token.md
        - title: User Management
          sections:
            - title: Add User
              link: docs/APIs/User-Management/Add-User.md
            - title: Inquire User
              link: docs/APIs/User-Management/Inquire-User.md
            - title: Inquire User Access
              link: docs/APIs/User-Management/Inquire-User-access.md
            - title: Update User
              link: docs/APIs/User-Management/Update-User.md
            - title: Update User Access
              link: docs/APIs/User-Management/Update-User-Access.md
