openapi: 3.0.1
info:
  title: Vision10 API Documentation
  description: V10 open API document.
  version: 1.0.0
servers:
- url: https://stg34.visionplus.io:24500/fva_apac
tags:
- name: Security
paths:
  /v1/getAccessToken:
    post:
      tags:
      - Security
      summary: Get Access Token
      description: This service is used to get Access Token to authenticate other
        Api
      operationId: GetAccessToken
      parameters:
      - name: X-Correl-Id
        in: header
        description: Any correlational text client's may want to send in the request
          for mapping the response on their side. Any value passed in the request
          message will be return back as-is in the API response message
        required: false
        schema:
          maxLength: 40
          type: string
          example: ABC123
      - name: X-Name
        in: header
        description: User’s sign-on name. The value passed in this field will be validated
          within application for user's authority to consume the requested API
        required: true
        schema:
          maxLength: 20
          type: string
          example: 00000AUNAB
      - name: X-context
        in: header
        description: A unique random ID assigned to the requestor once authenticated
          to the First Vision application. Value passed in this field will be used
          within application to authenticate the valid signed-on user
        required: true
        schema:
          maxLength: 20
          type: string
          example: 00000AUNAB
      responses:
        '404':
          description: " \nThe request resource does not exist"
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResponseErrorMessageInfo'
        '401':
          description: " \nThe request was unauthorized"
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResponseErrorMessageInfo'
        '504':
          description: " \nThe request timed out while waiting for a response"
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResponseErrorMessageInfo'
        '500':
          description: " \nAn unexpected internal server error occurred"
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResponseErrorMessageInfo'
        '400':
          description: " \nThe request cannot be validated"
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResponseErrorMessageInfo'
        '503':
          description: " \nThe service was unavailable"
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResponseErrorMessageInfo'
      security:
      - authorization: [
          ]
      x-proxy-name: Get Access Token
      x-group-name: Security
components:
  schemas:
    ResponseErrorMessageInfo:
      type: object
      properties:
        status:
          type: string
          example: ''
        detail:
          type: string
          example: ''
        title:
          type: string
          example: ''
        instance:
          type: string
          example: ''
        Source:
          type: string
          example: ''
        invalid-params:
          type: array
          items:
            type: string
  securitySchemes:
    authorization:
      type: http
      scheme: basic
