openapi: 3.0.1
info:
  title: Vision10 API Documentation
  description: V10 open API document.
  version: 1.0.0
servers:
- url: http://localhost:8080/
paths: {
  }
components:
  schemas: {
    }
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
