openapi: 3.0.1
info:
  title: Vision10 API Documentation
  description: V10 open API document.
  version: 1.0.0
servers:
  - url: https://stg34.visionplus.io:24500/fva_apac
tags:
  - name: User Management
paths:
  /v1/users/signOn:
    post:
      tags:
        - User Management
      summary: User Signon
      description: This service is used for user Signon
      operationId: UserSignon
      parameters:
        - name: X-Correl-Id
          in: header
          description: Any correlational text client's may want to send in the request for mapping the response on their side. Any value passed in the request message will be return back as-is in the API response message
          required: true
          schema:
            type: string
            example: ABC123
        - name: X-Name
          in: header
          description: User’s sign-on name. The value passed in this field will be validated within application for user's authority to consume the requested API
          required: true
          schema:
            type: string
            example: 00000AUNAB
        - name: X-context
          in: header
          description: A unique random ID assigned to the requestor once authenticated to the First Vision application. Value passed in this field will be used within application to authenticate the valid signed-on user
          required: true
          schema:
            type: string
            example: 00000AUNAB
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSignonReqModel'
      responses:
        '200':
          description: |2-
             
            Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSignonResponseModel'
        '400':
          description: |2-
             
            The request cannot be validated
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResponseErrorMessageInfo'
        '401':
          description: |2-
             
            The request was unauthorized
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResponseErrorMessageInfo'
        '404':
          description: |2-
             
            The request resource does not exist
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResponseErrorMessageInfo'
        '500':
          description: |2-
             
            An unexpected internal server error occurred
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResponseErrorMessageInfo'
        '503':
          description: |2-
             
            The service was unavailable
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResponseErrorMessageInfo'
        '504':
          description: |2-
             
            The request timed out while waiting for a response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResponseErrorMessageInfo'
components:
  schemas:
    UserSignonReqModel:
      required:
        - secret
        - securityName
      type: object
      properties:
        secret:
          maxLength: 512
          type: string
          description: Encrypted Data 1 - Password for signing on to the system
          example: A3CDCAE523A132FFAE3800958AC12AB7B62E0DA876C4C91A10C9AC4FF7DF18BF6940F5AEAF33BA381522594D03108CB7A8B46FF39BEE944A98DD26201F36ACFA71D15A875947741961188B661123BF507AB6A9D5E82BA5083D0DB98F54E6D857D9A5B4A48D2750A81A405563B656352230D9613D80F3A362867C1C59BBA09FFED3669DE30905631A4DD9DF68CA47F6E58A0987CCDECBEBD72229F8312684F7E3A5DBDB7E1F99690B7AD44A645EBA0D3BC5CD26F411E6FBED3F430BD2BA372118D934350A7BAC7DBD18BFDB54B3DEFCBC24A8C75768C3C9C766FE75AD3032BAFED6F886F02692DD1C38FF6088088069B281CFF12F745606F758932E83301878CA
        securityName:
          maxLength: 128
          type: string
          description: Security Name - Sign-on name assigned to the person signing on to the system
          example: 00001NABTEST5
    UserSignonResponseModel:
      type: object
      properties:
        securityContext:
          maxLength: 20
          type: string
          description: Security Context - This field is the security context of the person signing on to the system
          example: '00004753153543545'
    ResponseErrorMessageInfo:
      type: object
      properties:
        errorCode:
          type: string
        errorMessage:
          type: string
